version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./backend/alembic:/app/alembic
  frontend:
    build: ./frontend
    container_name: nextjs_app
    restart: always
    depends_on:
      - backend
    networks:
      - backend
    # volumes:
    #   - ./frontend:/app
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx

networks:
  backend:

volumes:
  pgdata:
  certbot-etc:
  certbot-var:
  certbot-www:
