version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env.dev
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./alembic:/app/alembic
  # alembic:
  #   build: .
  #   container_name: alembic_migration
  #   command: alembic upgrade head
  #   restart: "no"
  #   env_file:
  #     - .env.dev
  #   depends_on:
  #     - db
  #   networks:
  #     - backend
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=timeflow
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=timeflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - app
    networks:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx

networks:
  backend:

volumes:
  pgdata:
  certbot-etc:
  certbot-var:
  certbot-www:
