"""Language fix

Revision ID: 9dd34a0ff56b
Revises: 6564afc8c4a8
Create Date: 2025-03-25 19:43:41.510290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd34a0ff56b'
down_revision: Union[str, None] = '6564afc8c4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_language_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_language_key', 'users', ['language'])
    # ### end Alembic commands ###
