"""Verified field

Revision ID: b5060667056d
Revises: 574bd3f92658
Create Date: 2025-04-10 17:33:43.022826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5060667056d'
down_revision: Union[str, None] = '574bd3f92658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_user_id_fkey', 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('flows', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('flows_user_id_fkey', 'flows', type_='foreignkey')
    op.drop_constraint('flows_card_id_fkey', 'flows', type_='foreignkey')
    op.create_foreign_key(None, 'flows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'flows', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'flows', type_='foreignkey')
    op.drop_constraint(None, 'flows', type_='foreignkey')
    op.create_foreign_key('flows_card_id_fkey', 'flows', 'cards', ['card_id'], ['id'])
    op.create_foreign_key('flows_user_id_fkey', 'flows', 'users', ['user_id'], ['id'])
    op.alter_column('flows', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key('cards_user_id_fkey', 'cards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
